### ISSUE TITLE
Linear layer macs?

### ISSUE THREAD

**Issue by FlyGreyWolf** [frgfm/torch-scan#50] opened 2022-05-07 02:04 UTC
Why the  macs of linear layer equals 1 ?

**Comment by frgfm** [comment] 2022-05-07 10:04
Hi @FlyGreyWolf 👋 

So for a linear layer :
- input of shape (N, C1)
- weights of shape (C2, C1) (and bias C2)
- for N=1, the total number of atomatic operations is C2 * C1 multiplications + C2 summations (accumulations) + C2 bias summations
- Now a MAC stands for Multiply-Accumulate, which is an operation that takes into account the hardware architecture of modern computers (multiply + accumulate are done on the same chip at the same time, to make it short). So here it's C2*C1 MACs

As you can see here 👉 https://github.com/frgfm/torch-scan/blob/master/torchscan/modules/macs.py#L60, that doesn't yield a constant 1 and follow my explanation above!

Please let me know if things aren't clear :)

**Comment by frgfm** [comment] 2022-05-16 23:02
Closing this issue as it looks like there isn't any problem with the code base! Feel free to reopen if that's not the case @FlyGreyWolf :)

**Comment by FlyGreyWolf** [comment] 2022-05-17 03:04
Thanks for your response! But I do have this problem. 
For example: this is my code
```
from torchscan import summary
import torch.nn as nn

class Linear(nn.Module):
    def __init__(self):
        super(Linear, self).__init__()
        self.layer2 = nn.Linear(10, 5)

    def forward(self, x):
        x = self.layer2(x)
        return x

if __name__ == '__main__':
    linear = Linear()
    summary(linear, (1, 10), max_depth=0)
```

And the output is as follows:
```
__________________________________________________________________________________________
Layer                        Type                  Output Shape              Param #        
==========================================================================================
linear                       Linear                (-1, 1, 5)                55             
==========================================================================================
Trainable params: 55
Non-trainable params: 0
Total params: 55
------------------------------------------------------------------------------------------
Model size (params + buffers): 0.00 Mb
Framework & CUDA overhead: 1113.00 Mb
Total RAM usage: 1113.00 Mb
------------------------------------------------------------------------------------------
Floating Point Operations on forward: 6.00 FLOPs
Multiply-Accumulations on forward: 1.00 MACs
Direct memory accesses on forward: 70.00 DMAs
__________________________________________________________________________________________
```
Why the Multiply-Accumulations on forward: 1.00 MACs ? 

Thanks for your reply and answer again. Sincerely.

**Comment by frgfm** [comment] 2022-05-17 12:05
Let me try to reproduce this and get back to you 👍

**Comment by FlyGreyWolf** [comment] 2022-05-17 12:38
> Let me try to reproduce this and get back to you 👍

Ok, thank you very much.

**Comment by frgfm** [comment] 2022-05-17 15:14
Alright, so I have good news:
- first, in your snippet, you don't need to specify the batch size `summary(linear, (10,), max_depth=0)`
- this wasn't very clear in the doc, I just fixed that
- however linear works with high dimensions tensors, I fixed the computation for those cases & added a dedicated unittest 👍 

Once the PR is merged, everything should be good :) Let me know if you encounter other problems!

**Comment by FlyGreyWolf** [comment] 2022-05-17 15:32
> Alright, so I have good news:
> 
> * first, in your snippet, you don't need to specify the batch size `summary(linear, (10,), max_depth=0)`
> * this wasn't very clear in the doc, I just fixed that
> * however linear works with high dimensions tensors, I fixed the computation for those cases & added a dedicated unittest 👍
> 
> Once the PR is merged, everything should be good :) Let me know if you encounter other problems!

Thanks for your reply and your great work! I just tried to run your changes and found that they output normally.

**Closed** 2022-05-17 17:23 UTC
Labels: question, module: modules
